name: Hello Action

on:
  push:
    branches:
      - "githubActionsTest"
  pull_request:
    branches:
      - "githubActionsTest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello step
        run: echo "Hello World"
