name: PlatformIO CI CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run wifiTest
        run: pio test -e win_test_wifi -f "test_win_wifi"

      - name: Run pc_comm test
        run: pio test -e win_test_pc_comm -f "test_win_pc_comm"

      - name: Run Light test
        run: pio test -e win_test_light -f "test_win_light"

      - name: Run dht11 controller test
        run: pio test -e win_test_light -f "test_win_dht11_controller"

      - name: Run proximity test
        run: pio test -e win_test_light -f "test_win_proximity"

      - name: Run serial number test
        run: pio test -e win_test_light -f "test_win_serial"

      - name: Run status test
        run: pio test -e win_test_light -f "test_win_status"
